# Generated by Django 5.2.1 on 2025-06-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AplicativosUtilizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ConhecimentoMirantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FonteInformacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Insatisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='LocaisVisitados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacaoEmEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Percepcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_expectativa', models.IntegerField()),
                ('qualidade_dos_servicos_turisticos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('br', 'Brasil'), ('ar', 'Argentina'), ('de', 'Germany'), ('fr', 'France')], max_length=2, verbose_name='país do turista')),
                ('estado', models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais'), ('RS', 'Rio Grande do Sul')], max_length=50, verbose_name='estado')),
                ('cidade', models.CharField(choices=[('sao_paulo', 'São Paulo'), ('rio', 'Rio de Janeiro'), ('bh', 'Belo Horizonte'), ('poa', 'Porto Alegre')], max_length=50, verbose_name='cidade')),
                ('faixa_etaria', models.IntegerField(choices=[(0, '18 a 24 anos'), (1, '25 a 34 anos'), (2, '35 a 44 anos'), (3, '45 a 54 anos'), (4, '55 a 64 anos'), (5, '65 anos ou mais')], verbose_name='faixa etária')),
                ('genero', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('non_binary', 'Não binário'), ('other', 'Outro'), ('omit', 'Prefiro nao informar')], max_length=50, verbose_name='genero')),
                ('escolaridade', models.IntegerField(choices=[(0, 'Ensino fundamental incompleto'), (1, 'Ensino fundamental completo'), (2, 'Ensino médio incompleto'), (3, 'Ensino médio completo'), (4, 'Ensino superior incompleto'), (5, 'Ensino superior completo')], verbose_name='escolaridade do turista')),
                ('renda_estimada', models.CharField(choices=[('low', 'Menos de R$1.000'), ('low_mid', 'R$1.000 - R$3.000'), ('mid', 'R$3.000 - R$5.000'), ('high_mid', 'R$5.000 - R$10.000'), ('high', 'Mais de R$10.000'), ('omit', 'Prefiro não informar')], max_length=10, verbose_name='renda estimada')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadesRealizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicativos', models.ManyToManyField(to='form.aplicativosutilizados')),
                ('locais_visitados', models.ManyToManyField(to='form.locaisvisitados')),
                ('participacao_em_eventos', models.ManyToManyField(to='form.participacaoemeventos')),
            ],
        ),
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viagem_planejada', models.BooleanField(default=False)),
                ('antecedencia_do_planejamento', models.IntegerField(choices=[(0, 'Menos de 1 mês'), (1, '1 a 3 meses'), (2, '3 a 6 meses'), (3, 'Mais de 6 meses')], verbose_name='antecedência do planejamento')),
                ('forma_de_organizacao', models.IntegerField(choices=[(0, 'Viagem individual'), (1, 'Viagem em casal'), (2, 'Viagem em família'), (3, 'Viagem em grupo'), (4, 'Com agência de viagens'), (5, 'Outro')], verbose_name='forma de organização')),
                ('fontes_de_informacao_utilizadas', models.ManyToManyField(to='form.fonteinformacao')),
            ],
        ),
        migrations.CreateModel(
            name='Satisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfacao_geral_com_a_visita', models.IntegerField()),
                ('intencao_de_retorno', models.IntegerField()),
                ('recomendacao_do_destino', models.IntegerField()),
                ('insatisfacao_com_a_visita', models.ManyToManyField(to='form.insatisfacao')),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ja_visitou', models.BooleanField(default=False)),
                ('conhece_a_rota_mirantes', models.BooleanField(default=False)),
                ('tempo_de_estadia', models.IntegerField(choices=[(0, '1 dia'), (1, '2 a 3 dias'), (2, 'Apenas no final de semana'), (3, '4 dias'), (4, '5 dias'), (5, '1 semana'), (6, '15 dias'), (7, 'Mais de 15 dias')])),
                ('reincidencia', models.IntegerField(choices=[(0, 'Já visitei entre 2 e 5 vezes'), (1, 'Já visitei entre 5 e 10 vezes'), (2, 'Já visitei mais de 10 vezes'), (3, 'Visito uma vez por mês'), (4, 'Visito a cada fim de semana')])),
                ('gasto_diario_estimado', models.IntegerField(choices=[(0, 'Até R$ 300,00'), (1, 'De R$ 300,00 a R$ 500,00'), (2, 'De R$ 500,00 a R$ 1.000,00'), (3, 'De R$ 1.000,00 a R$ 1.500,00'), (4, 'De R$ 1.500,00 a R$ 2.000,00'), (5, 'De R$ 2.000,00 a R$ 3.000,00'), (6, 'De R$ 3.000,00 a R$ 5.000,00'), (7, 'Acima de R$ 5.000,00')])),
                ('como_soube_dos_mirantes', models.ManyToManyField(to='form.conhecimentomirantes')),
                ('motivo', models.ManyToManyField(to='form.motivo')),
                ('tipo_de_hospedagem', models.ManyToManyField(to='form.tipohospedagem')),
                ('veiculo_utilizado', models.ManyToManyField(to='form.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ComportamentoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisou_de_algum_servico', models.CharField(max_length=255)),
                ('viagens', models.ManyToManyField(to='form.viagem')),
            ],
        ),
    ]
