# Generated by Django 5.2.1 on 2025-06-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percepcao',
            name='qualidade_dos_servicos_turisticos',
        ),
    ]
