# Generated by Django 5.2.1 on 2025-06-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planejamento',
            name='antecedencia_do_planejamento',
            field=models.IntegerField(choices=[(1, 'Menos de 1 mês'), (2, '1 a 3 meses'), (3, '3 a 6 meses'), (4, 'Mais de 6 meses')], verbose_name='antecedência do planejamento'),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='forma_de_organizacao',
            field=models.IntegerField(choices=[(1, 'Viagem individual'), (2, 'Viagem em casal'), (3, 'Viagem em família'), (4, 'Viagem em grupo'), (5, 'Com agência de viagens'), (6, 'Outro')], verbose_name='forma de organização'),
        ),
        migrations.AlterField(
            model_name='turista',
            name='escolaridade',
            field=models.IntegerField(choices=[(1, 'Ensino fundamental incompleto'), (2, 'Ensino fundamental completo'), (3, 'Ensino médio incompleto'), (4, 'Ensino médio completo'), (5, 'Ensino superior incompleto'), (6, 'Ensino superior completo')], verbose_name='escolaridade do turista'),
        ),
        migrations.AlterField(
            model_name='turista',
            name='faixa_etaria',
            field=models.IntegerField(choices=[(1, '18 a 24 anos'), (2, '25 a 34 anos'), (3, '35 a 44 anos'), (4, '45 a 54 anos'), (5, '55 a 64 anos'), (6, '65 anos ou mais')], verbose_name='faixa etária'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='gasto_diario_estimado',
            field=models.IntegerField(choices=[(1, 'Até R$ 300,00'), (2, 'De R$ 300,00 a R$ 500,00'), (3, 'De R$ 500,00 a R$ 1.000,00'), (4, 'De R$ 1.000,00 a R$ 1.500,00'), (5, 'De R$ 1.500,00 a R$ 2.000,00'), (6, 'De R$ 2.000,00 a R$ 3.000,00'), (7, 'De R$ 3.000,00 a R$ 5.000,00'), (8, 'Acima de R$ 5.000,00')]),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='reincidencia',
            field=models.IntegerField(choices=[(1, 'Já visitei entre 2 e 5 vezes'), (2, 'Já visitei entre 5 e 10 vezes'), (3, 'Já visitei mais de 10 vezes'), (4, 'Visito uma vez por mês'), (5, 'Visito a cada fim de semana')]),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='tempo_de_estadia',
            field=models.IntegerField(choices=[(1, '1 dia'), (2, '2 a 3 dias'), (3, 'Apenas no final de semana'), (4, '4 dias'), (5, '5 dias'), (6, '1 semana'), (7, '15 dias'), (8, 'Mais de 15 dias')]),
        ),
    ]
