# Generated by Django 5.2.1 on 2025-06-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_percepcao_qualidade_dos_servicos_turisticos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfacao_geral_com_a_visita', models.IntegerField()),
                ('nivel_expectativa', models.IntegerField()),
                ('nivel_satisfacao', models.IntegerField()),
                ('intencao_de_retorno', models.IntegerField()),
                ('precisou_de_algum_servico', models.CharField(max_length=255)),
                ('insatisfacao_com_a_visita', models.ManyToManyField(to='form.insatisfacao')),
            ],
        ),
        migrations.RemoveField(
            model_name='comportamentodigital',
            name='viagens',
        ),
        migrations.DeleteModel(
            name='Percepcao',
        ),
        migrations.RemoveField(
            model_name='satisfacao',
            name='insatisfacao_com_a_visita',
        ),
        migrations.DeleteModel(
            name='ComportamentoDigital',
        ),
        migrations.DeleteModel(
            name='Satisfacao',
        ),
    ]
