# Generated by Django 5.2.1 on 2025-06-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_planejamento_antecedencia_do_planejamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turista',
            name='data_resposta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
