# Generated by Django 5.2.7 on 2025-11-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_turista_data_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicativosutilizados',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='precisou_de_algum_servico',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='conhecimentomirantes',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fonteinformacao',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='insatisfacao',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='planejamento',
            name='antecedencia_do_planejamento',
            field=models.IntegerField(blank=True, choices=[(0, 'Não informado'), (1, 'Menos de 1 mês'), (2, '1 a 3 meses'), (3, '3 a 6 meses'), (4, 'Mais de 6 meses')], null=True, verbose_name='antecedência do planejamento'),
        ),
        migrations.AlterField(
            model_name='turista',
            name='cidade',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='turista',
            name='escolaridade',
            field=models.IntegerField(choices=[(1, 'Ensino fundamental incompleto'), (2, 'Ensino fundamental completo'), (3, 'Ensino médio incompleto'), (4, 'Ensino médio completo'), (5, 'Ensino superior incompleto'), (6, 'Ensino superior completo'), (7, 'Especialização'), (8, 'MBA'), (9, 'Mestrado'), (10, 'Doutorado'), (11, 'Pós-doutorado')], verbose_name='escolaridade do turista'),
        ),
        migrations.AlterField(
            model_name='turista',
            name='estado',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='turista',
            name='pais',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='reincidencia',
            field=models.IntegerField(blank=True, choices=[(0, 'Não informado'), (1, 'Visitei entre 2 e 5 vezes'), (2, 'Visitei entre 5 e 10 vezes'), (3, 'Visitei mais de 10 vezes'), (4, 'Visito uma vez por mês'), (5, 'Visito a cada fim de semana')], null=True),
        ),
    ]
